source = $HOME/.config/hypr/themes/colors.conf

general {
    hide_cursor = false
}

background {
    monitor =

    color = #ff9900
}

# ─────────────────────────────────────────────
# DAY
# ─────────────────────────────────────────────

label {
    monitor =

    text = cmd[update:60000] date '+%A'

    color = $accent

    font_family = Noto Sans Bold
    font_size = 26

    position = -110, 130
    halign = center
    valign = center
}

# ─────────────────────────────────────────────
# DATE
# ─────────────────────────────────────────────

label {
    monitor =

    text = cmd[update:60000] date '+%d %B %Y'

    color = $secondary

    font_family = Noto Sans
    font_size = 14
    font_weight = 400

    position = 110, 130
    halign = center
    valign = center
}

# ─────────────────────────────────────────────
# TIME
# ─────────────────────────────────────────────

label {
    monitor =

    text = $TIME

    color = $text

    font_family = Noto Sans
    font_size = 58
    font_weight = 700

    position = 0, 62
    halign = center
    valign = center

    shadow_passes = 2
    shadow_size = 3
    shadow_color = $background
    shadow_boost = 0.55
}

# ─────────────────────────────────────────────
# PASSWORD
# ─────────────────────────────────────────────

input-field {
    monitor =

    size = 330, 58

    outline_thickness = 0
    rounding = -1

    inner_color = $sunken
    font_color = $accent

    font_family = Noto Sans
    font_size = 13
    font_weight = 400

    dots_size = 0.22
    dots_spacing = 0.16
    dots_center = true
    dots_rounding = -1

    fade_on_empty = false

    placeholder_text = Enter password

    check_color = $accent
    fail_color = $accent

    fail_text = $FAIL
    fail_timeout = 1800

    capslock_color = $sunken
    numlock_color = $sunken
    bothlock_color = $sunken

    position = 0, -25
    halign = center
    valign = center
}

# ─────────────────────────────────────────────
# KEYBOARD LAYOUT
# ─────────────────────────────────────────────

label {
    monitor =

    text = $LAYOUT[EN,FA]

    color = $secondary

    font_family = Noto Sans
    font_size = 12
    font_weight = 500

    onclick = hyprctl switchxkblayout all next

    position = 0, -82
    halign = center
    valign = center
}

# ─────────────────────────────────────────────
# CAPS LOCK
# ─────────────────────────────────────────────

label {
    monitor =

    text = cmd[update:500] sh -c '
        for f in /sys/class/leds/*capslock/brightness; do
            if [ -f "$f" ] && [ "$(cat "$f")" = "1" ]; then
                printf "Caps Lock"
                break
            fi
        done
    '

    color = $accent

    font_family = Noto Sans
    font_size = 11
    font_weight = 500

    position = 0, -112
    halign = center
    valign = center
}
