monitor=HDMI-0,1920x1080@180,0x0,1
monitor=eDP-1-1,disable

env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = NVD_BACKEND,direct

cursor {
    no_hardware_cursors = true
}

general {
    gaps_in = 0
    gaps_out = 0
    border_size = 1
    allow_tearing = false
}

decoration {
    rounding = 0

    blur {
        enabled = false
    }

    shadow {
        enabled = false
    }
}

animations {
    enabled = false
}

input {
    kb_layout = us
}

bind = SUPER, RETURN, exec, kitty
bind = SUPER, Q, killactive
bind = SUPER, M, exit